# Generated by Django 4.1.7 on 2023-08-09 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="department",
            options={"verbose_name_plural": "部门管理"},
        ),
        migrations.AlterModelOptions(
            name="dmin",
            options={"verbose_name_plural": "登录用户管理"},
        ),
        migrations.AlterModelOptions(
            name="prettynum",
            options={"verbose_name_plural": "号码管理"},
        ),
        migrations.AlterModelOptions(
            name="task",
            options={"verbose_name_plural": "任务管理"},
        ),
        migrations.AlterModelOptions(
            name="userinfo",
            options={"verbose_name_plural": "普通用户管理"},
        ),
        migrations.CreateModel(
            name="Orderpanhe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("oid", models.CharField(max_length=64, verbose_name="订单号")),
                ("title", models.CharField(max_length=32, verbose_name="名称")),
                ("price", models.DateTimeField(verbose_name="开始时间")),
                ("endtime", models.DateTimeField(verbose_name="结束时间")),
                (
                    "status",
                    models.SmallIntegerField(
                        choices=[(1, "待使用"), (2, "已使用")], default=1, verbose_name="状态"
                    ),
                ),
                (
                    "admin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app01.dmin",
                        verbose_name="管理员",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("oid", models.CharField(max_length=64, verbose_name="订单号")),
                ("title", models.CharField(max_length=32, verbose_name="名称")),
                ("price", models.DateTimeField(verbose_name="开始时间")),
                ("endtime", models.DateTimeField(verbose_name="结束时间")),
                (
                    "status",
                    models.SmallIntegerField(
                        choices=[(1, "待使用"), (2, "已使用")], default=1, verbose_name="状态"
                    ),
                ),
                (
                    "admin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app01.dmin",
                        verbose_name="管理员",
                    ),
                ),
            ],
        ),
    ]
