# Generated by Django 4.1.7 on 2023-08-09 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0002_alter_department_options_alter_dmin_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Departmentpanhe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=32, verbose_name="标题")),
            ],
            options={
                "verbose_name_plural": "部门管理",
            },
        ),
    ]
